# Generated by Django 4.2.1 on 2023-06-09 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='apellidomaterno',
            field=models.CharField(default='ApellidoMaternoPorDefecto', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellidopaterno',
            field=models.CharField(default='ApellidoPaternoPorDefecto', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='pais',
            field=models.CharField(default='PaisPorDefecto', max_length=100),
        ),
    ]
