# Generated by Django 4.2.1 on 2023-06-09 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_apellidomaterno_usuario_apellidopaterno_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='apellidomaterno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='apellidopaterno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='pais',
            field=models.CharField(max_length=100),
        ),
    ]
